version: '3.8'
services:
  nginx:
    image: docker.pkg.github.com/zyryf/splittingbills/nginx:1.0.0
    ports:
      - 80:80
      - 443:443
  client:
    image: docker.pkg.github.com/zyryf/splittingbills/client:1.0.0
    environment:
      - NODE_ENV=production
    command: "http-server dist"
  server:
    image: docker.pkg.github.com/zyryf/splittingbills/server:1.0.0
    environment:
      - NODE_ENV=production
      - DATASOURCE_URL=${DATASOURCE_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    command: "npm run start"
